### ISSUE TITLE
HTTP /render endpoint not returning data

### ISSUE THREAD

**Issue by dekdaas** [tgres/tgres#22]
What is the correct format for querying data from the render endpoint?
I am running tgres in Docker with a Postgres instance and I am populating the ts table with 
`while true; do echo -n "carbon.823:$((RANDOM % 100))|c" | nc -w 1 -u 127.0.0.1 8125; done` in a separate terminal. I see data in the ts table, but all of my queries at the HTTP /render endpoint returns "SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data". I am (for the most part) formatting queries such that they work with Graphite.

Example queries:
[localhost:8888/render?target=carbon.823](url)
[localhost:8888/render?target=stats.cabon.823](url)
[http://localhost:8888/render/?target\=stats.carbon.823\&from\=-1d\&maxDataPoints\=100](url)

**Comment by grisha** [comment]
`/render` follows the Graphite format, but i'd check to make sure you have stuff in the database first - rather than looking at the `ts` table, look at `dsv` (your `carbon.823...` should be listed there), `rrav` should have a list of rras for that ds_id, and finally `tv` should have the actual data points in human-readable format.
